#%RAML 1.0
---
title: DanStroot API
baseUri: http://danstroot.com/{version}
version: v1

/users:
  /customerfocus:
  get:
  post:
  /systemsthinker:
  get:
  queryparameters:
    classification:
    author:
    how_to_apply:
  post:
  
  
  /traits:
    /{fairness}:
    get:
    post:
    /{honesty}:
    get:
    post:
  
  /action_oriented:
  get:
  post:
  
  /alignment(many paths lead to same destination):
  get:
  post:
  
  /definition_of_done
  get:
  post:
  
  
